import { UserProfile, MasterGlowPlan, FullReading, AchievementLog, Recipe, GlowAudit } from '../types';

export const DEFAULT_USER_PROFILE: UserProfile = {
  language: 'en',
  gender: 'female',
  age: 24,
  weight: 60,
  height: 168,
  weightUnit: 'kg',
  heightUnit: 'cm',
  fitnessLevel: 'intermediate',
  activitySchedulePreference: '07:30 AM',
  primaryGoals: [
    'Restorative Deep Sleep & Circadian Alignment',
    'Postural Spine Alignment (Reverse Tech Neck)',
    'Glass Skin Radiance & Hydration',
    'Toned Body Silhouette & Lean Muscle',
    'Mental Calm & Emotional Balance',
  ],
  dietaryPreference: 'Anti-Inflammatory High Protein',
  concerns: 'Slight morning face puffiness, forward head posture from computer work, late bedtime',
  glowStreak: 5,
  totalXp: 450,
  glowLevel: 2,
  themeMode: 'dark',
  waterGlassesToday: 5,
  sleepProfile: {
    currentBedtime: '00:30',
    targetBedtime: '22:30',
    wakeTime: '06:30',
    screenFreeMinutes: 45,
    gradualStepIndex: 1,
    windDownCompletedToday: false,
  },
};

export const COMMON_FRIDGE_ITEMS = [
  'Eggs',
  'Spinach',
  'Greek Yogurt',
  'Chicken Breast',
  'Avocado',
  'Cucumbers',
  'Blueberries',
  'Salmon',
  'Olive Oil',
  'Sweet Potato',
  'Broccoli',
  'Almond Milk',
  'Lemon & Limes',
  'Chia Seeds',
  'Bell Peppers',
  'Tofu',
  'Garlic & Ginger',
  'Oats',
  'Tomatoes',
  'Feta Cheese',
  'Cottage Cheese',
  'Zucchini',
  'Walnuts',
  'Kimchi',
];

export const DEFAULT_READINGS: FullReading[] = [
  {
    id: 'reading-1',
    dayNumber: 1,
    title: 'The Nervous System & Facial Tension: The Hidden Key to Natural Glow',
    topic: 'Mental Health & Aesthetics',
    estimatedReadMinutes: 10,
    keyInsight: 'Facial beauty and structural harmony are directly compromised when the autonomic nervous system holds chronic sub-perceptual tension.',
    sections: [
      {
        heading: '1. The Somatic Mask We Wear',
        content:
          'When we navigate modern screen-heavy, high-stress environments, our masseter muscles clench, our corrugator supercilii (eyebrow knitters) contract, and our breathing shifts to shallow chest gasps. This constricts micro-capillaries in the dermal layer, impeding lymph drainage and dulling skin tone. Recognizing this somatic mask is the first step to unlocking an effortless, radiant face.',
      },
      {
        heading: '2. The Vagus Nerve and Skin Elasticity',
        content:
          'Dermatological research confirms that prolonged elevated cortisol inhibits fibroblast proliferation, directly slowing collagen and elastin synthesis. Engaging vagal tone through prolonged nasal exhales, cold facial immersion, and unclenching the palate triggers instant parasympathetic rejuvenation, allowing cellular repair enzymes to flourish.',
      },
      {
        heading: '3. The Ritual of Facial Ease',
        content:
          'Practice resting your tongue completely flat against the entire roof of your mouth while keeping your teeth slightly apart and your lips gently sealed. Drop your shoulders away from your earlobes. Feel the space behind your eyes soften. Notice how this physical adjustment immediately conveys sovereign calm and aesthetic poise.',
      },
    ],
    actionableTakeaways: [
      'Perform 5 cycles of 4-second nasal inhale, 7-second exhale to soften your jaw and brow.',
      'Maintain tongue-to-palate posture (proper oral resting posture) throughout desk work.',
      'Log one moment today where you caught yourself holding tension and consciously released it.',
    ],
    reflectionPrompt: 'Where in your face and body do you habitually hold stress, and what will you do to create lightness there today?',
    completed: true,
  },
  {
    id: 'reading-2',
    dayNumber: 2,
    title: 'Postural Sovereignty: The Biomechanics of Magnetic Presence',
    topic: 'Body Language & Posture',
    estimatedReadMinutes: 10,
    keyInsight: 'Your cervical and thoracic spine alignment determines how your jawline attaches, how your clothes drape, and how the world responds to you.',
    sections: [
      {
        heading: '1. The Kinetic Chain of the Silhouette',
        content:
          'A forward head posture of just 2 inches places an effective 32 pounds of extra strain on the upper cervical vertebrae and pulls the platysma muscle down. This softens the submental angle (creating the illusion of a double chin even at low body fat) and collapses the ribcage. When you retract the chin and activate the lower trapezius, the jawline instantly sharpens by up to 25%.',
      },
      {
        heading: '2. Opening the Heart Center',
        content:
          'Rounded shoulders are a biological defense posture mimicking fear. When you deliberately externally rotate the humerus and depress the scapulae, you physically signal high internal safety and composure. Your lung capacity expands by up to 15%, increasing oxygen delivery to every tissue in your body.',
      },
      {
        heading: '3. Grounded Gravity Walk',
        content:
          'Walk with the sensation of being gently suspended by the crown of your head while your heels strike softly and your glutes stabilize each step. Let your gaze rest on the horizon rather than your smartphone.',
      },
    ],
    actionableTakeaways: [
      'Do 3 sets of 10 wall angels before your morning workout.',
      'Elevate your computer monitor to eye-level to protect cervical alignment.',
      'Walk for 10 minutes with shoulders relaxed back and crown floating high.',
    ],
    reflectionPrompt: 'How does standing at your absolute tallest change your internal self-talk and confidence?',
    completed: false,
  },
  {
    id: 'reading-3',
    dayNumber: 3,
    title: 'Nutritional Alchemy: Micronutrients for Collagen, Clarity & Satiety',
    topic: 'Nutrition & Skin Glow',
    estimatedReadMinutes: 10,
    keyInsight: 'Food is biological code that instructs your epigenetic expression—feed your cells polyphenols, amino acids, and hydration for radiant vitality.',
    sections: [
      {
        heading: '1. The Anti-Glycation Protocol',
        content:
          'Advanced Glycation End-products (AGEs) occur when excess sugars cross-link with collagen fibers, making skin stiff, fragile, and prone to dullness. By pairing complex carbohydrates with clean proteins, fiber, and healthy monounsaturated fats (like olive oil and avocado), you stabilize blood glucose, preventing glycemic spikes and supporting skin suppleness.',
      },
      {
        heading: '2. Cellular Hydration vs Plain Water',
        content:
          'Drinking 3 liters of distilled water without minerals can paradoxically flush out essential electrolytes. True cellular plumpness requires potassium, magnesium, and sodium to pull fluid inside the intracellular space, creating that lit-from-within glow without tissue puffiness.',
      },
      {
        heading: '3. The Anti-Boredom Plate',
        content:
          'Healthy eating fails when it becomes monotonous. Adding acidic elements (lemon, balsamic, pickled onions), fresh herbs (cilantro, mint, basil), and warming spices (turmeric, smoked paprika) transforms clean whole foods into gourmet culinary experiences.',
      },
    ],
    actionableTakeaways: [
      'Add a pinch of Celtic sea salt or a squeeze of fresh lemon to your morning water.',
      'Include a colorful antioxidant source (berries, dark leafy greens, bell peppers) in every main meal.',
      'Avoid high-glycemic snacks 2 hours before bedtime to protect nightly human growth hormone (HGH) release.',
    ],
    reflectionPrompt: 'Which nutrient-rich ingredient will you incorporate today to nourish your skin and energy?',
    completed: false,
  },
];

export const DEFAULT_MASTER_PLAN: MasterGlowPlan = {
  targetCalories: 1850,
  proteinGrams: 125,
  carbsGrams: 175,
  fatGrams: 55,
  waterLiters: 3.0,
  weeklyPlan: [
    {
      dayNumber: 1,
      dayName: 'Monday',
      focus: 'Jawline Definition & Upper Body Posture Reset',
      workout: {
        title: 'V-Taper Silhouette & Cervical Spine Alignment',
        scheduledTime: '07:30 AM',
        durationMinutes: 45,
        caloriesBurned: 330,
        isRestDay: false,
        focusArea: 'Upper Body & Posture',
        exercises: [
          {
            name: 'Face Pulls with High External Rotation',
            sets: 4,
            reps: '15 reps',
            restSeconds: 60,
            formTip: 'Pull rope toward forehead while pulling knuckles apart; feel rear delts and mid-traps burn to reverse forward neck tilt.',
            category: 'posture',
          },
          {
            name: 'Dumbbell Lateral Raises (Strict Temp)',
            sets: 4,
            reps: '12-15 reps',
            restSeconds: 60,
            formTip: 'Slightly lean torso forward, lead with elbows to cap off the shoulders and broaden the upper silhouette.',
            category: 'strength',
          },
          {
            name: 'Incline Dumbbell Neutral Press',
            sets: 3,
            reps: '10-12 reps',
            restSeconds: 75,
            formTip: 'Open collarbone wide, pinch shoulder blades into the bench to expand thoracic ribcage.',
            category: 'strength',
          },
          {
            name: 'Wall Angels & Prone Cobras',
            sets: 3,
            reps: '12 slow reps',
            restSeconds: 45,
            formTip: 'Keep lower back, elbows, and wrists glued to the wall throughout the sliding motion.',
            category: 'mobility',
          },
          {
            name: 'Jawline & Platysma Neck Extension Sculpt',
            sets: 3,
            reps: '15 reps',
            restSeconds: 30,
            formTip: 'Tilt head up at 45 degrees, place tongue firmly on roof of mouth, and gently extend lower jaw upward.',
            category: 'face_neck',
          },
        ],
      },
      faceRoutine: {
        morning: '30-second ice bowl plunge + 3-min lymphatic drainage Gua Sha sweep along jawline + Vitamin C & SPF 50',
        evening: 'Gentle hydrating cleanse + 4-min pterygoid masseter release & cheekbone lift + Peptide night cream',
      },
      dailySchedule: [
        {
          time: '07:00 AM',
          category: 'face',
          title: 'Ice Immersion & Lymphatic Awakening',
          description: 'Depuff eyes, boost microcirculation, and sharpen jawline contour.',
          duration: 10,
          completed: true,
        },
        {
          time: '07:30 AM',
          category: 'body',
          title: 'Scheduled Workout: V-Taper & Posture Reset',
          description: '45-minute structured resistance and cervical spine strengthening.',
          duration: 45,
          completed: true,
        },
        {
          time: '08:30 AM',
          category: 'nutrition',
          title: 'Glow Breakfast: High-Protein & Antioxidants',
          description: '35g protein meal + 750ml mineralized lemon water.',
          duration: 25,
          completed: true,
        },
        {
          time: '12:45 PM',
          category: 'nutrition',
          title: 'Metabolic Balance Lunch & Hydration',
          description: 'Clean whole grains, fibrous greens, lean protein & 750ml water.',
          duration: 30,
          completed: false,
        },
        {
          time: '05:30 PM',
          category: 'mind',
          title: '10-Minute Daily Reading Sanctuary',
          description: 'Read "The Nervous System & Facial Tension" + take note in Achievement Book.',
          duration: 10,
          completed: false,
        },
        {
          time: '07:30 PM',
          category: 'nutrition',
          title: 'Collagen-Supportive Dinner',
          description: 'Light anti-inflammatory dinner cooked with fresh fridge ingredients.',
          duration: 35,
          completed: false,
        },
        {
          time: '09:30 PM',
          category: 'mind',
          title: 'Book of Achievements & Evening Winddown',
          description: 'Log 3 daily wins, masseter facial massage, and screen curfew.',
          duration: 15,
          completed: false,
        },
      ],
      readingSnippet: {
        title: 'The Nervous System & Facial Tension',
        category: 'Mental Health & Aesthetics',
        readTime: '10 min',
        summary: 'How releasing hidden jaw and eyebrow clenching restores youthful facial symmetry and skin radiance.',
      },
      dailyAchievementGoals: [
        'Completed 45-min posture & lift session',
        'Hit 3.0L water target with electrolytes',
        'Performed morning jawline sculpt & cold plunge',
        'Completed 10 minutes of mental glow reading',
        'Stayed within target calorie and protein window',
      ],
    },
    {
      dayNumber: 2,
      dayName: 'Tuesday',
      focus: 'Glute/Lower Body Sculpt & Dermal Hydration',
      workout: {
        title: 'Lower Body Kinetic Power & Core Stability',
        scheduledTime: '07:30 AM',
        durationMinutes: 50,
        caloriesBurned: 390,
        isRestDay: false,
        focusArea: 'Lower Body & Core',
        exercises: [
          {
            name: 'Barbell/Dumbbell Romanian Deadlifts',
            sets: 4,
            reps: '10-12 reps',
            restSeconds: 90,
            formTip: 'Hinge back deeply through hips; keep spine flat to build hamstring-glute tie-in and spinal erector strength.',
            category: 'strength',
          },
          {
            name: 'Bulgarian Split Squats (Glute Bias)',
            sets: 3,
            reps: '10 reps/side',
            restSeconds: 75,
            formTip: 'Slight torso forward lean; drive upward through mid-foot to isolate glute medius and sculpt hips.',
            category: 'strength',
          },
          {
            name: 'Standing Calf Raises & Ankle Mobility',
            sets: 3,
            reps: '15 reps',
            restSeconds: 45,
            formTip: 'Full stretch at bottom and 2-second squeeze at top to enhance leg taper and venous blood return.',
            category: 'strength',
          },
          {
            name: 'Deadbugs & Hollow Body Holds',
            sets: 3,
            reps: '45 seconds',
            restSeconds: 45,
            formTip: 'Press lumbar spine into mat, engaging transverse abdominis for a naturally cinched waistline.',
            category: 'posture',
          },
        ],
      },
      faceRoutine: {
        morning: 'Chilled green tea toner splash + Niacinamide serum + Zygomatic cheekbone tap massage + SPF',
        evening: 'Double cleanse + Retinol 0.3% + 5-min gentle neck lymph sweep toward clavicle',
      },
      dailySchedule: [
        {
          time: '07:00 AM',
          category: 'face',
          title: 'Morning Skincare & Cheek Lift',
          description: 'Microcirculation stimulation and antioxidant barrier protection.',
          duration: 10,
        },
        {
          time: '07:30 AM',
          category: 'body',
          title: 'Lower Body Kinetic Sculpt',
          description: '50-minute targeted posterior chain resistance.',
          duration: 50,
        },
        {
          time: '08:45 AM',
          category: 'nutrition',
          title: 'Post-Workout Anabolic Glow Shake',
          description: 'Whey/plant protein, blueberries, spinach, and chia seeds.',
          duration: 15,
        },
        {
          time: '01:00 PM',
          category: 'nutrition',
          title: 'Lean Fuel Lunch & 1L Water',
          description: 'Grilled salmon or tofu with quinoa and avocado salad.',
          duration: 30,
        },
        {
          time: '05:30 PM',
          category: 'mind',
          title: '10-Minute Reading: Postural Sovereignty',
          description: 'Deep dive into biomechanics and magnetizing presence.',
          duration: 10,
        },
        {
          time: '07:30 PM',
          category: 'nutrition',
          title: 'Fridge Chef Anti-Inflammatory Dinner',
          description: 'Creative seasonal stir-fry with zero food boredom.',
          duration: 30,
        },
        {
          time: '09:30 PM',
          category: 'mind',
          title: 'Book of Achievements Entry',
          description: 'Celebrate crushing your lower body workout & log learnings.',
          duration: 15,
        },
      ],
      readingSnippet: {
        title: 'Postural Sovereignty',
        category: 'Body Language & Posture',
        readTime: '10 min',
        summary: 'How thoracic expansion and head alignment shape your jawline and projected authority.',
      },
      dailyAchievementGoals: [
        'Hit 50-minute lower body workout',
        'Drank full 3L electrolyte hydration',
        'Applied morning & evening targeted skincare',
        'Completed 10-minute Postural Sovereignty reading',
        'Logged 3 accomplishments in Book of Achievements',
      ],
    },
    {
      dayNumber: 3,
      dayName: 'Wednesday',
      focus: 'Active Recovery, Face Yoga & Gut-Skin Harmony',
      workout: {
        title: 'Lymphatic Walk, Spine Decompression & Face Yoga',
        scheduledTime: '07:30 AM',
        durationMinutes: 40,
        caloriesBurned: 220,
        isRestDay: false,
        focusArea: 'Mobility & Face Sculpt',
        exercises: [
          {
            name: 'Brisk Incline Zone 2 Walk (8,000 Step Goal)',
            sets: 1,
            reps: '30 mins',
            restSeconds: 0,
            formTip: 'Nasal breathing only; actively swing arms to pump lymphatic fluid through nodes.',
            category: 'cardio',
          },
          {
            name: 'Cat-Cow & Thoracic Rotation Openers',
            sets: 3,
            reps: '10 reps each',
            restSeconds: 30,
            formTip: 'Mobilize every single vertebrae to relieve desk-bound compression.',
            category: 'mobility',
          },
          {
            name: 'Cheekbone Lifter & Jawline Scoop Face Yoga',
            sets: 3,
            reps: '10 reps (5s hold)',
            restSeconds: 30,
            formTip: 'O-shape with mouth, smile with upper lip while lifting cheek muscles up toward temples.',
            category: 'face_neck',
          },
        ],
      },
      faceRoutine: {
        morning: 'Cold roller face sweep + Hyaluronic acid on damp skin + Ceramide barrier defense + SPF',
        evening: 'Deep cleansing oil + Warm towel steam + Rosehip seed oil facial massage + Lymph drainage',
      },
      dailySchedule: [
        {
          time: '07:15 AM',
          category: 'face',
          title: 'Face Yoga & Ice Roller Treatment',
          description: 'Natural lifting of zygomaticus and buccal fat reduction massage.',
          duration: 15,
        },
        {
          time: '07:30 AM',
          category: 'body',
          title: 'Brisk Incline Lymphatic Walk',
          description: 'Zone 2 aerobic flush to detoxify tissue and boost cellular metabolism.',
          duration: 35,
        },
        {
          time: '08:30 AM',
          category: 'nutrition',
          title: 'Gut-Skin Probiotic Bowl',
          description: 'Greek yogurt or kefir with berries, walnuts, and flaxseed.',
          duration: 20,
        },
        {
          time: '01:00 PM',
          category: 'nutrition',
          title: 'Nutrient-Dense Fridge Salad',
          description: 'Cruciferous veggies, olive oil, and high-quality protein.',
          duration: 30,
        },
        {
          time: '05:30 PM',
          category: 'mind',
          title: '10-Minute Reading: Nutritional Alchemy',
          description: 'Discover how micronutrients stimulate collagen synthesis.',
          duration: 10,
        },
        {
          time: '07:30 PM',
          category: 'nutrition',
          title: 'Slow-Digesting Nourishment Dinner',
          description: 'Hearty veggie & protein stew seasoned with ginger and turmeric.',
          duration: 35,
        },
        {
          time: '09:30 PM',
          category: 'mind',
          title: 'Gratitude & Achievement Reflection',
          description: 'Record progress milestones and 8-hour sleep preparation.',
          duration: 15,
        },
      ],
      readingSnippet: {
        title: 'Nutritional Alchemy',
        category: 'Nutrition & Skin Glow',
        readTime: '10 min',
        summary: 'Feeding your cells with anti-glycation compounds to protect natural collagen.',
      },
      dailyAchievementGoals: [
        'Completed 30-min brisk outdoor/incline walk',
        'Practiced 10-min face yoga and cold roll',
        'Ate probiotic gut-health meal',
        'Finished 10-min daily reading drop',
        'Recorded victory in Achievement Book',
      ],
    },
    {
      dayNumber: 4,
      dayName: 'Thursday',
      focus: 'Upper Body Aesthetics, Shoulder Caps & Jawline Sharpness',
      workout: {
        title: 'Shoulders, Arms & Scapular Retraction',
        scheduledTime: '07:30 AM',
        durationMinutes: 45,
        caloriesBurned: 310,
        isRestDay: false,
        focusArea: 'Upper Body Aesthetics',
        exercises: [
          {
            name: 'Overhead Dumbbell Shoulder Press',
            sets: 3,
            reps: '10-12 reps',
            restSeconds: 75,
            formTip: 'Lock out overhead with ribs down and core tight; builds capped shoulders that make the waist look smaller.',
            category: 'strength',
          },
          {
            name: 'Cable / Band Face Pulls',
            sets: 4,
            reps: '15 reps',
            restSeconds: 60,
            formTip: 'Pinch scapulae and thumbs back to elevate thoracic posture.',
            category: 'posture',
          },
          {
            name: 'Incline Dumbbell Bicep Curls & Tricep Dips',
            sets: 3,
            reps: '12 reps each',
            restSeconds: 60,
            formTip: 'Full stretch at bottom of curl to elongate the bicep muscle belly.',
            category: 'strength',
          },
          {
            name: 'Submental Jawline Presses',
            sets: 3,
            reps: '20 reps',
            restSeconds: 30,
            formTip: 'Fist under chin, open mouth against gentle upward resistance to tighten digastric muscles.',
            category: 'face_neck',
          },
        ],
      },
      faceRoutine: {
        morning: 'Cold water splash + Vitamin C serum + 3-min Gua Sha + SPF 50',
        evening: 'Double cleanse + AHA exfoliant + Hydrating peptide mask + Masseter release',
      },
      dailySchedule: [
        {
          time: '07:00 AM',
          category: 'face',
          title: 'Ice Compression & Jawline Sculpt',
          description: 'Sharp morning jawline contouring routine.',
          duration: 10,
        },
        {
          time: '07:30 AM',
          category: 'body',
          title: 'Upper Body Aesthetic Sculpt',
          description: '45-minute focus on shoulder caps, posture, and arm definition.',
          duration: 45,
        },
        {
          time: '08:45 AM',
          category: 'nutrition',
          title: 'High-Protein Breakfast',
          description: '35g clean protein + antioxidant green tea.',
          duration: 20,
        },
        {
          time: '01:00 PM',
          category: 'nutrition',
          title: 'Balanced Glow Lunch',
          description: 'Grilled chicken or lentils with crisp Mediterranean salad.',
          duration: 30,
        },
        {
          time: '05:30 PM',
          category: 'mind',
          title: '10-Minute Reading: The Stoic Glow Frame',
          description: 'Developing unshakeable internal poise.',
          duration: 10,
        },
        {
          time: '07:30 PM',
          category: 'nutrition',
          title: 'Fridge Chef Dinner',
          description: 'Anti-inflammatory stir-fry from fridge leftovers.',
          duration: 35,
        },
        {
          time: '09:30 PM',
          category: 'mind',
          title: 'Achievement Book Milestone Log',
          description: 'Record day 4 wins and check weekly consistency.',
          duration: 15,
        },
      ],
      readingSnippet: {
        title: 'The Stoic Glow Frame',
        category: 'Mental Mastery & Poise',
        readTime: '10 min',
        summary: 'How emotional sovereignty removes facial stress micro-expressions and radiates natural charisma.',
      },
      dailyAchievementGoals: [
        'Completed upper body aesthetic session',
        'Drank 3.0L water',
        'Ate within calorie and macro targets',
        'Read 10-min Stoic Glow module',
        'Logged 3 wins in Achievement Book',
      ],
    },
    {
      dayNumber: 5,
      dayName: 'Friday',
      focus: 'Full Body Athletic Tone & High-Energy Glow',
      workout: {
        title: 'Full Body Athletic Conditioning & Core Vacuum',
        scheduledTime: '07:30 AM',
        durationMinutes: 45,
        caloriesBurned: 370,
        isRestDay: false,
        focusArea: 'Full Body & Core Conditioning',
        exercises: [
          {
            name: 'Goblet Squats with 2-Sec Pause',
            sets: 3,
            reps: '12 reps',
            restSeconds: 60,
            formTip: 'Chest tall, knees out, pause at depth to maximize quad and glute activation.',
            category: 'strength',
          },
          {
            name: 'Push-Up to Downward Dog Flow',
            sets: 3,
            reps: '10 reps',
            restSeconds: 60,
            formTip: 'Drive heels down in dog pose to decompress hamstrings and lengthen spine.',
            category: 'posture',
          },
          {
            name: 'Stomach Vacuums (Transverse Abdominis Sculpt)',
            sets: 4,
            reps: '20-sec hold',
            restSeconds: 45,
            formTip: 'Exhale all air completely, suck navel to spine, hold to tighten internal abdominal corset.',
            category: 'posture',
          },
          {
            name: 'Kettlebell/Dumbbell Swings',
            sets: 3,
            reps: '20 reps',
            restSeconds: 60,
            formTip: 'Powerful hip snap for explosive posterior chain activation and metabolic burn.',
            category: 'cardio',
          },
        ],
      },
      faceRoutine: {
        morning: 'Cold cucumber water mist + Niacinamide + Under-eye ice spoon + SPF 50',
        evening: 'Deep double cleanse + Squalane oil facial glide + 5-min neck lymphatic sweep',
      },
      dailySchedule: [
        {
          time: '07:00 AM',
          category: 'face',
          title: 'Morning Skin Glow Prep',
          description: 'De-puffing and antioxidant surge for the weekend.',
          duration: 10,
        },
        {
          time: '07:30 AM',
          category: 'body',
          title: 'Full Body Athletic Sculpt',
          description: 'Cardio conditioning and core vacuum training.',
          duration: 45,
        },
        {
          time: '08:45 AM',
          category: 'nutrition',
          title: 'Post-Workout Fuel & Hydration',
          description: 'Oatmeal with whey protein, chia seeds, and berries.',
          duration: 20,
        },
        {
          time: '01:00 PM',
          category: 'nutrition',
          title: 'Energizing Lunch',
          description: 'Whole grain wrap with turkey/tofu, avocado, and spinach.',
          duration: 30,
        },
        {
          time: '05:30 PM',
          category: 'mind',
          title: '10-Minute Reading: The Sleep-Growth Hormone Axis',
          description: 'Harnessing restorative sleep for maximum physical transformation.',
          duration: 10,
        },
        {
          time: '07:30 PM',
          category: 'nutrition',
          title: 'Gourmet Fridge Chef Dinner',
          description: 'Nutrient-rich, satisfying meal to celebrate Friday night.',
          duration: 35,
        },
        {
          time: '09:30 PM',
          category: 'mind',
          title: 'Book of Achievements Weekly High Point',
          description: 'Record 5 day streak celebration in Achievement Book.',
          duration: 15,
        },
      ],
      readingSnippet: {
        title: 'The Sleep-Growth Hormone Axis',
        category: 'Recovery & Cellular Glow',
        readTime: '10 min',
        summary: 'How deep stage-3 sleep releases 70% of daily human growth hormone to rebuild skin and muscle tissue.',
      },
      dailyAchievementGoals: [
        'Finished full body athletic workout',
        'Practiced 4 sets of stomach vacuums',
        'Hit 3L water goal',
        'Read 10-min Sleep Optimization chapter',
        'Logged achievements and unlocked streak badge',
      ],
    },
    {
      dayNumber: 6,
      dayName: 'Saturday',
      focus: 'Outdoor Movement, Facial Sculpting & Mindful Nourishment',
      workout: {
        title: 'Outdoor Trail/Park Run & Dynamic Mobility',
        scheduledTime: '08:30 AM',
        durationMinutes: 45,
        caloriesBurned: 350,
        isRestDay: false,
        focusArea: 'Cardio & Nature Sunlight Glow',
        exercises: [
          {
            name: 'Sunlight Aerobic Walk / Jog',
            sets: 1,
            reps: '35 mins',
            restSeconds: 0,
            formTip: 'Receive morning sunlight in eyes (no sunglasses for first 15 mins) to optimize circadian cortisol rhythms.',
            category: 'cardio',
          },
          {
            name: 'Hip Flexor Couch Stretch & Quad Opener',
            sets: 3,
            reps: '60 sec/side',
            restSeconds: 30,
            formTip: 'Release tight psoas muscles to fix anterior pelvic tilt and flatter the lower abdomen.',
            category: 'mobility',
          },
          {
            name: 'Gua Sha Jawline & Clavicle Drainage',
            sets: 1,
            reps: '8 mins',
            restSeconds: 0,
            formTip: 'Light pressure; glide down neck to supraclavear notch to flush lymphatic waste.',
            category: 'face_neck',
          },
        ],
      },
      faceRoutine: {
        morning: 'Cold water plunge + Hyaluronic mist + Broad-spectrum mineral SPF 50',
        evening: 'Hydrating sheet mask + Jojoba oil face yoga sculpting + Ceramide barrier cream',
      },
      dailySchedule: [
        {
          time: '08:00 AM',
          category: 'face',
          title: 'Sunlight & Morning Hydration',
          description: '500ml water with sea salt & 15 mins natural morning photons.',
          duration: 15,
        },
        {
          time: '08:30 AM',
          category: 'body',
          title: 'Outdoor Sunlight Movement & Stretch',
          description: 'Circadian rhythm reset and hip mobility session.',
          duration: 45,
        },
        {
          time: '10:00 AM',
          category: 'nutrition',
          title: 'Weekend Glow Brunch',
          description: 'Poached eggs, smoked salmon, sautéed spinach & whole sourdough toast.',
          duration: 30,
        },
        {
          time: '02:00 PM',
          category: 'mind',
          title: '10-Minute Reading: Aesthetic Magnetism',
          description: 'Cultivating presence, active listening, and relaxed confidence.',
          duration: 10,
        },
        {
          time: '06:30 PM',
          category: 'nutrition',
          title: 'Fresh Fridge Creation Dinner',
          description: 'High-protein creative dinner with seasonal vegetables.',
          duration: 35,
        },
        {
          time: '09:00 PM',
          category: 'face',
          title: 'Weekend Deep Spa Facial & Gua Sha',
          description: 'Extended 15-min facial release and sheet mask.',
          duration: 20,
        },
        {
          time: '09:30 PM',
          category: 'mind',
          title: 'Book of Achievements Weekly Review',
          description: 'Document your glow transformations and wins.',
          duration: 15,
        },
      ],
      readingSnippet: {
        title: 'Aesthetic Magnetism',
        category: 'Presence & Communication',
        readTime: '10 min',
        summary: 'Why warmth and high internal competence create an aura far more compelling than physical symmetry alone.',
      },
      dailyAchievementGoals: [
        'Got 20+ minutes of natural morning sunlight',
        'Completed outdoor movement and mobility routine',
        'Enjoyed balanced high-protein weekend brunch',
        'Completed 10-minute Aesthetic Magnetism reading',
        'Logged weekend wins in Book of Achievements',
      ],
    },
    {
      dayNumber: 7,
      dayName: 'Sunday',
      focus: 'Deep Restoration, Weekly Audit & Transformation Checkpoint',
      workout: {
        title: 'Restorative Yin Yoga, Foam Rolling & Walk',
        scheduledTime: '09:00 AM',
        durationMinutes: 35,
        caloriesBurned: 160,
        isRestDay: true,
        focusArea: 'Active Restoration & Recovery',
        exercises: [
          {
            name: 'Full Body Foam Rolling (Lats, Quads, Calves)',
            sets: 1,
            reps: '15 mins',
            restSeconds: 0,
            formTip: 'Breathe into tight tender trigger points to dissolve myofascial knots.',
            category: 'mobility',
          },
          {
            name: 'Pigeon Pose & Butterfly Stretch',
            sets: 3,
            reps: '90 sec/side',
            restSeconds: 30,
            formTip: 'Deep hip opening to release stored emotional tension and improve pelvic alignment.',
            category: 'mobility',
          },
          {
            name: 'Legs Up the Wall (Viparita Karani)',
            sets: 1,
            reps: '10 mins',
            restSeconds: 0,
            formTip: 'Elevate legs against wall to dramatically accelerate venous return and systemic lymph drainage.',
            category: 'posture',
          },
        ],
      },
      faceRoutine: {
        morning: 'Gentle micellar water + Rosewater mist + Hyaluronic acid + SPF 50',
        evening: 'Weekly gentle enzyme peel + Overnight sleeping moisture mask + Masseter jaw release',
      },
      dailySchedule: [
        {
          time: '08:30 AM',
          category: 'mind',
          title: 'Slow Morning & Electrolyte Hydration',
          description: 'Gentle awakening with zero social media screen time.',
          duration: 20,
        },
        {
          time: '09:00 AM',
          category: 'body',
          title: 'Restorative Yin Yoga & Foam Roll',
          description: 'Myofascial release and deep parasympathetic reset.',
          duration: 35,
        },
        {
          time: '10:30 AM',
          category: 'nutrition',
          title: 'Weekly Meal Prep & Fridge Refresh',
          description: 'Organize high-protein snacks, clean veggies, and fridge pantry.',
          duration: 45,
        },
        {
          time: '02:00 PM',
          category: 'face',
          title: 'Weekly Before & After Photo Checkpoint',
          description: 'Take progress selfie, compare alignment, and audit transformation.',
          duration: 15,
        },
        {
          time: '05:00 PM',
          category: 'mind',
          title: '10-Minute Reading: The Identity Shift',
          description: 'Embodying the person who naturally lives in peak health and beauty.',
          duration: 10,
        },
        {
          time: '07:00 PM',
          category: 'nutrition',
          title: 'Nutrient-Dense Sunday Dinner',
          description: 'Balanced comfort meal fueling the upcoming week.',
          duration: 35,
        },
        {
          time: '09:00 PM',
          category: 'mind',
          title: 'Weekly Book of Achievements Crown Entry',
          description: 'Award yourself the 7-Day Glow Warrior badge and set goals for next week.',
          duration: 20,
        },
      ],
      readingSnippet: {
        title: 'The Identity Shift',
        category: 'Transformation Psychology',
        readTime: '10 min',
        summary: 'Why lasting physical and mental transformation only happens when your fundamental self-image catches up with your daily habits.',
      },
      dailyAchievementGoals: [
        'Completed Sunday Yin recovery session',
        'Took weekly Before/After photo comparison',
        'Prepped clean groceries for the week ahead',
        'Finished 10-minute Identity Shift reading',
        'Logged entire week in Book of Achievements',
      ],
    },
  ],
};

export const INITIAL_ACHIEVEMENTS: AchievementLog[] = [
  {
    id: 'ach-1',
    date: '2026-08-20',
    title: '30-Sec Morning Cold Face Plunge & Gua Sha',
    category: 'face',
    note: 'Face immediately felt lighter, puffiness under eyes disappeared.',
    xpEarned: 50,
  },
  {
    id: 'ach-2',
    date: '2026-08-21',
    title: 'Crushed 45-Min Posture & V-Taper Workout',
    category: 'body',
    note: 'Hit 4 sets of face pulls with strict form. Felt thoracic spine lengthen.',
    xpEarned: 100,
  },
  {
    id: 'ach-3',
    date: '2026-08-21',
    title: 'Completed 10-Minute Daily Reading Sanctuary',
    category: 'mind',
    note: 'Read chapter on vagus nerve & unclenching the jaw. Practiced palate posture all afternoon.',
    xpEarned: 75,
  },
  {
    id: 'ach-4',
    date: '2026-08-22',
    title: 'Created High-Protein Fridge Chef Scramble (420 kcal)',
    category: 'nutrition',
    note: 'Used leftover spinach, eggs, and feta. Hit 28g protein without ordering takeout!',
    xpEarned: 60,
  },
];

export const INITIAL_SAMPLE_RECIPES: Recipe[] = [
  {
    id: 'rec-1',
    name: 'Glow Goddess Spinach & Feta Scramble with Toasted Sourdough',
    mealType: 'Breakfast',
    prepTimeMinutes: 10,
    calories: 420,
    proteinGrams: 28,
    carbsGrams: 24,
    fatGrams: 22,
    usedIngredients: ['Eggs', 'Spinach', 'Feta Cheese', 'Olive Oil'],
    pantryAdditions: ['Black Pepper', 'Sea Salt', 'Smoked Paprika', 'Lemon Squeeze'],
    instructions: [
      'Heat 1 tsp olive oil in a non-stick pan over medium heat; sauté baby spinach with garlic powder until wilted (90s).',
      'Whisk 3 eggs with sea salt and cracked black pepper; pour over spinach.',
      'Gently fold on low heat until soft curds form; fold in crumbled feta cheese right before removing from heat.',
      'Serve over warm artisan sourdough with a fresh squeeze of lemon juice.',
    ],
    glowBenefit: 'Choline in egg yolks feeds cell membranes, while lutein in spinach protects against oxidative skin aging.',
    boredomBusterTip: 'Drizzle with a dash of hot honey or balsamic glaze for an elevated restaurant flavor profile.',
  },
  {
    id: 'rec-2',
    name: 'Crispy Pan-Seared Salmon with Warm Lemon-Herb Quinoa Salad',
    mealType: 'Dinner',
    prepTimeMinutes: 20,
    calories: 540,
    proteinGrams: 42,
    carbsGrams: 35,
    fatGrams: 24,
    usedIngredients: ['Salmon', 'Cucumbers', 'Olive Oil', 'Lemon & Limes', 'Tomatoes'],
    pantryAdditions: ['Dried Oregano', 'Flaky Sea Salt', 'Garlic', 'Cooked Quinoa'],
    instructions: [
      'Pat salmon dry with a paper towel; season skin generously with sea salt.',
      'Sear skin-side down in olive oil for 5 minutes on medium-high until golden and crisp; flip for 2 more minutes.',
      'Dice cucumbers and tomatoes; toss with warm quinoa, lemon juice, oregano, and 1 tsp extra virgin olive oil.',
      'Top the zesty salad with the crispy salmon fillet and fresh cracked pepper.',
    ],
    glowBenefit: 'Astaxanthin and Omega-3 fatty acids in wild salmon increase skin moisture barrier and reduce systemic inflammation.',
    boredomBusterTip: 'Add diced kalamata olives and fresh mint leaves for a Greek-island culinary flair.',
  },
  {
    id: 'rec-3',
    name: 'Creamy Berry & Greek Yogurt Protein Parfait with Chia Crunch',
    mealType: 'Snack',
    prepTimeMinutes: 5,
    calories: 310,
    proteinGrams: 26,
    carbsGrams: 32,
    fatGrams: 8,
    usedIngredients: ['Greek Yogurt', 'Blueberries', 'Chia Seeds', 'Walnuts'],
    pantryAdditions: ['Cinnamon', 'Honey or Stevia', 'Vanilla extract'],
    instructions: [
      'Layer 1 cup non-fat Greek yogurt mixed with a drop of vanilla extract into a glass bowl.',
      'Top with fresh blueberries, 1 tbsp chia seeds, and crushed walnuts.',
      'Dust with ground cinnamon and a light drizzle of raw honey.',
    ],
    glowBenefit: 'Probiotics in Greek yogurt promote a diverse gut microbiome, directly preventing acne and skin redness.',
    boredomBusterTip: 'Freeze for 20 minutes before eating to create a refreshing frozen-yogurt consistency.',
  },
];

export const INITIAL_SAMPLE_AUDIT: GlowAudit = {
  id: 'audit-initial',
  auditDate: '2026-08-20',
  glowScore: 78,
  potentialScore: 97,
  faceAnalysis: {
    jawlineDefinition: 'Good underlying bone structure; slight morning lymphatic fluid retention along the jaw angle.',
    skinClarity: 'Even warm undertone; slight barrier dehydration and screen fatigue around orbital area.',
    eyeVitality: 'Clear and alert; subtle dark circles indicating need for optimized REM sleep and cold compresses.',
    facialSymmetry: 'High natural cheekbone symmetry; highly responsive to lymphatic Gua Sha and daily ice plunges.',
    keyFaceTips: [
      '30-second ice bowl immersion upon waking to drain facial edema',
      'Correct tongue posture (resting on hard and soft palate) to strengthen jawline definition',
      'Hyaluronic acid on damp skin followed by peptide sealant for glass-skin luminescence',
    ],
  },
  bodyAnalysis: {
    postureAlignment: 'Mild forward head angle (6-8 degrees) from computer usage; scapulae slightly protracted.',
    compositionEstimate: 'Athletic baseline; targeted V-taper exercises and glute work will immediately sharpen proportions.',
    neckShoulderTension: 'Trapezius muscle tightness pulling collarbones upward.',
    keyBodyTips: [
      'Face pulls and chin tucks 3x per week to instantly reverse screen slouch',
      'Daily 10-minute brisk walk with shoulders depressed and head crown floating',
      'Stomach vacuums to tighten transverse abdominis and naturally narrow waistline',
    ],
  },
  keyStrengths: [
    'Excellent zygomatic (cheekbone) prominence',
    'Clear, high-contrast natural eye shape',
    'Responsive athletic musculature and high aesthetic upside',
  ],
  focusAreas: [
    'Submental jawline contouring & lymphatic drainage',
    'Cervical spine and scapular retraction',
    'Hydration and antioxidant dermal barrier defense',
    'Stress cortisol downregulation via 10-min evening mindset reading',
  ],
  postGlowProtocol: {
    nutritionSummary: 'Target 1,850 kcal (125g protein, 175g carbs, 55g fats) with 3.0L electrolyte water.',
    workoutSummary: '4-day resistance split focusing on posture supersets, shoulder caps, and lower body shape.',
    faceCareSummary: 'AM ice dip + Vitamin C + Gua Sha; PM retinol + peptide massage and masseter relaxation.',
    mindSummary: '10 minutes of daily strategic glow reading + logging 3 daily wins in Book of Achievements.',
  },
};
